version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=pasan
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://admin1:XQy0%2A4%7B%5CM%3DR%27UFAR@34.42.79.184/eduwave?sslmode=disable
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
volumes:
  data-volume:
