// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: course_enrolments.sql

package db

import (
	"context"
)

const createEnrolments = `-- name: CreateEnrolments :one
INSERT INTO course_enrolments (
    course_id,
    request_id,
    user_id
) VALUES (
    $1, $2, $3
) RETURNING enrolment_id, course_id, request_id, user_id
`

type CreateEnrolmentsParams struct {
	CourseID  int64 `json:"course_id"`
	RequestID int64 `json:"request_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) CreateEnrolments(ctx context.Context, arg CreateEnrolmentsParams) (CourseEnrolment, error) {
	row := q.queryRow(ctx, q.createEnrolmentsStmt, createEnrolments, arg.CourseID, arg.RequestID, arg.UserID)
	var i CourseEnrolment
	err := row.Scan(
		&i.EnrolmentID,
		&i.CourseID,
		&i.RequestID,
		&i.UserID,
	)
	return i, err
}

const getEnrolment = `-- name: GetEnrolment :one
SELECT enrolment_id, course_id, request_id, user_id FROM course_enrolments
WHERE user_id = $1  AND course_id = $2
`

type GetEnrolmentParams struct {
	UserID   int64 `json:"user_id"`
	CourseID int64 `json:"course_id"`
}

func (q *Queries) GetEnrolment(ctx context.Context, arg GetEnrolmentParams) (CourseEnrolment, error) {
	row := q.queryRow(ctx, q.getEnrolmentStmt, getEnrolment, arg.UserID, arg.CourseID)
	var i CourseEnrolment
	err := row.Scan(
		&i.EnrolmentID,
		&i.CourseID,
		&i.RequestID,
		&i.UserID,
	)
	return i, err
}

const listEnrolments = `-- name: ListEnrolments :many
SELECT enrolment_id, course_id, request_id, user_id FROM course_enrolments
WHERE course_id = $1 
ORDER BY enrolment_id
LIMIT $2
OFFSET $3
`

type ListEnrolmentsParams struct {
	CourseID int64 `json:"course_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListEnrolments(ctx context.Context, arg ListEnrolmentsParams) ([]CourseEnrolment, error) {
	rows, err := q.query(ctx, q.listEnrolmentsStmt, listEnrolments, arg.CourseID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseEnrolment{}
	for rows.Next() {
		var i CourseEnrolment
		if err := rows.Scan(
			&i.EnrolmentID,
			&i.CourseID,
			&i.RequestID,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnrolmentsByUser = `-- name: ListEnrolmentsByUser :many
SELECT enrolment_id, course_id, request_id, user_id FROM course_enrolments
WHERE user_id = $1 
ORDER BY enrolment_id
LIMIT $2
OFFSET $3
`

type ListEnrolmentsByUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListEnrolmentsByUser(ctx context.Context, arg ListEnrolmentsByUserParams) ([]CourseEnrolment, error) {
	rows, err := q.query(ctx, q.listEnrolmentsByUserStmt, listEnrolmentsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseEnrolment{}
	for rows.Next() {
		var i CourseEnrolment
		if err := rows.Scan(
			&i.EnrolmentID,
			&i.CourseID,
			&i.RequestID,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
