// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: requests.sql

package db

import (
	"context"
	"database/sql"
)

const createRequest = `-- name: CreateRequest :one
INSERT INTO requests (
    is_active,
    is_pending,
    is_accepted,
    is_declined
) VALUES (
    $1, $2, $3, $4
) RETURNING request_id, student_id, teacher_id, course_id, is_active, is_pending, is_accepted, is_declined
`

type CreateRequestParams struct {
	IsActive   sql.NullBool `json:"is_active"`
	IsPending  sql.NullBool `json:"is_pending"`
	IsAccepted sql.NullBool `json:"is_accepted"`
	IsDeclined sql.NullBool `json:"is_declined"`
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error) {
	row := q.db.QueryRowContext(ctx, createRequest,
		arg.IsActive,
		arg.IsPending,
		arg.IsAccepted,
		arg.IsDeclined,
	)
	var i Request
	err := row.Scan(
		&i.RequestID,
		&i.StudentID,
		&i.TeacherID,
		&i.CourseID,
		&i.IsActive,
		&i.IsPending,
		&i.IsAccepted,
		&i.IsDeclined,
	)
	return i, err
}

const deleteRequest = `-- name: DeleteRequest :exec
DELETE FROM requests
WHERE request_id = $1
`

func (q *Queries) DeleteRequest(ctx context.Context, requestID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRequest, requestID)
	return err
}

const getRequest = `-- name: GetRequest :one
SELECT request_id, student_id, teacher_id, course_id, is_active, is_pending, is_accepted, is_declined FROM requests
WHERE request_id = $1
`

func (q *Queries) GetRequest(ctx context.Context, requestID int64) (Request, error) {
	row := q.db.QueryRowContext(ctx, getRequest, requestID)
	var i Request
	err := row.Scan(
		&i.RequestID,
		&i.StudentID,
		&i.TeacherID,
		&i.CourseID,
		&i.IsActive,
		&i.IsPending,
		&i.IsAccepted,
		&i.IsDeclined,
	)
	return i, err
}

const listRequest = `-- name: ListRequest :many
SELECT request_id, student_id, teacher_id, course_id, is_active, is_pending, is_accepted, is_declined FROM requests
WHERE student_id = $1 AND teacher_id = $2 AND course_id =$3
ORDER BY request_id
LIMIT $4
OFFSET $5
`

type ListRequestParams struct {
	StudentID sql.NullInt64 `json:"student_id"`
	TeacherID sql.NullInt64 `json:"teacher_id"`
	CourseID  sql.NullInt64 `json:"course_id"`
	Limit     int32         `json:"limit"`
	Offset    int32         `json:"offset"`
}

func (q *Queries) ListRequest(ctx context.Context, arg ListRequestParams) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, listRequest,
		arg.StudentID,
		arg.TeacherID,
		arg.CourseID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.RequestID,
			&i.StudentID,
			&i.TeacherID,
			&i.CourseID,
			&i.IsActive,
			&i.IsPending,
			&i.IsAccepted,
			&i.IsDeclined,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRequests = `-- name: UpdateRequests :one
UPDATE requests
SET is_active = $4, is_pending = $5, is_accepted = $6, is_declined = $7 
WHERE student_id = $1 AND teacher_id = $2 AND course_id =$3
RETURNING request_id, student_id, teacher_id, course_id, is_active, is_pending, is_accepted, is_declined
`

type UpdateRequestsParams struct {
	StudentID  sql.NullInt64 `json:"student_id"`
	TeacherID  sql.NullInt64 `json:"teacher_id"`
	CourseID   sql.NullInt64 `json:"course_id"`
	IsActive   sql.NullBool  `json:"is_active"`
	IsPending  sql.NullBool  `json:"is_pending"`
	IsAccepted sql.NullBool  `json:"is_accepted"`
	IsDeclined sql.NullBool  `json:"is_declined"`
}

func (q *Queries) UpdateRequests(ctx context.Context, arg UpdateRequestsParams) (Request, error) {
	row := q.db.QueryRowContext(ctx, updateRequests,
		arg.StudentID,
		arg.TeacherID,
		arg.CourseID,
		arg.IsActive,
		arg.IsPending,
		arg.IsAccepted,
		arg.IsDeclined,
	)
	var i Request
	err := row.Scan(
		&i.RequestID,
		&i.StudentID,
		&i.TeacherID,
		&i.CourseID,
		&i.IsActive,
		&i.IsPending,
		&i.IsAccepted,
		&i.IsDeclined,
	)
	return i, err
}
