// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: requests.sql

package db

import (
	"context"
	"database/sql"
)

const createRequest = `-- name: CreateRequest :one
INSERT INTO requests (
    user_id,
    course_id,
    is_active,
    is_pending,
    is_accepted,
    is_declined
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING request_id, user_id, course_id, is_active, is_pending, is_accepted, is_declined, created_at
`

type CreateRequestParams struct {
	UserID     int64        `json:"user_id"`
	CourseID   int64        `json:"course_id"`
	IsActive   sql.NullBool `json:"is_active"`
	IsPending  sql.NullBool `json:"is_pending"`
	IsAccepted sql.NullBool `json:"is_accepted"`
	IsDeclined sql.NullBool `json:"is_declined"`
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error) {
	row := q.queryRow(ctx, q.createRequestStmt, createRequest,
		arg.UserID,
		arg.CourseID,
		arg.IsActive,
		arg.IsPending,
		arg.IsAccepted,
		arg.IsDeclined,
	)
	var i Request
	err := row.Scan(
		&i.RequestID,
		&i.UserID,
		&i.CourseID,
		&i.IsActive,
		&i.IsPending,
		&i.IsAccepted,
		&i.IsDeclined,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRequest = `-- name: DeleteRequest :exec
DELETE FROM requests
WHERE request_id = $1
`

func (q *Queries) DeleteRequest(ctx context.Context, requestID int64) error {
	_, err := q.exec(ctx, q.deleteRequestStmt, deleteRequest, requestID)
	return err
}

const getRequest = `-- name: GetRequest :one
SELECT request_id, user_id, course_id, is_active, is_pending, is_accepted, is_declined, created_at FROM requests
WHERE request_id = $1 AND user_id = $2
`

type GetRequestParams struct {
	RequestID int64 `json:"request_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) GetRequest(ctx context.Context, arg GetRequestParams) (Request, error) {
	row := q.queryRow(ctx, q.getRequestStmt, getRequest, arg.RequestID, arg.UserID)
	var i Request
	err := row.Scan(
		&i.RequestID,
		&i.UserID,
		&i.CourseID,
		&i.IsActive,
		&i.IsPending,
		&i.IsAccepted,
		&i.IsDeclined,
		&i.CreatedAt,
	)
	return i, err
}

const listRequest = `-- name: ListRequest :many
SELECT request_id, user_id, course_id, is_active, is_pending, is_accepted, is_declined, created_at FROM requests
ORDER BY request_id
LIMIT $1
OFFSET $2
`

type ListRequestParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRequest(ctx context.Context, arg ListRequestParams) ([]Request, error) {
	rows, err := q.query(ctx, q.listRequestStmt, listRequest, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.RequestID,
			&i.UserID,
			&i.CourseID,
			&i.IsActive,
			&i.IsPending,
			&i.IsAccepted,
			&i.IsDeclined,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRequests = `-- name: UpdateRequests :one
UPDATE requests
SET is_active = $2, is_pending = $3, is_accepted = $4, is_declined = $5 
WHERE user_id = $1
RETURNING request_id, user_id, course_id, is_active, is_pending, is_accepted, is_declined, created_at
`

type UpdateRequestsParams struct {
	UserID     int64        `json:"user_id"`
	IsActive   sql.NullBool `json:"is_active"`
	IsPending  sql.NullBool `json:"is_pending"`
	IsAccepted sql.NullBool `json:"is_accepted"`
	IsDeclined sql.NullBool `json:"is_declined"`
}

func (q *Queries) UpdateRequests(ctx context.Context, arg UpdateRequestsParams) (Request, error) {
	row := q.queryRow(ctx, q.updateRequestsStmt, updateRequests,
		arg.UserID,
		arg.IsActive,
		arg.IsPending,
		arg.IsAccepted,
		arg.IsDeclined,
	)
	var i Request
	err := row.Scan(
		&i.RequestID,
		&i.UserID,
		&i.CourseID,
		&i.IsActive,
		&i.IsPending,
		&i.IsAccepted,
		&i.IsDeclined,
		&i.CreatedAt,
	)
	return i, err
}
