// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: resources.sql

package db

import (
	"context"
)

const createResource = `-- name: CreateResource :one
INSERT INTO resources (
    material_id,
    title,
    type,
    content_url
) VALUES (
    $1, $2, $3, $4
) RETURNING resource_id, material_id, title, type, content_url, created_at
`

type CreateResourceParams struct {
	MaterialID int64        `json:"material_id"`
	Title      string       `json:"title"`
	Type       TypeResource `json:"type"`
	ContentUrl string       `json:"content_url"`
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, createResource,
		arg.MaterialID,
		arg.Title,
		arg.Type,
		arg.ContentUrl,
	)
	var i Resource
	err := row.Scan(
		&i.ResourceID,
		&i.MaterialID,
		&i.Title,
		&i.Type,
		&i.ContentUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteResource = `-- name: DeleteResource :exec
DELETE FROM resources
WHERE resource_id = $1 AND material_id = $2
`

type DeleteResourceParams struct {
	ResourceID int64 `json:"resource_id"`
	MaterialID int64 `json:"material_id"`
}

func (q *Queries) DeleteResource(ctx context.Context, arg DeleteResourceParams) error {
	_, err := q.db.ExecContext(ctx, deleteResource, arg.ResourceID, arg.MaterialID)
	return err
}

const getResource = `-- name: GetResource :one
SELECT resource_id, material_id, title, type, content_url, created_at FROM resources
WHERE resource_id = $1
`

func (q *Queries) GetResource(ctx context.Context, resourceID int64) (Resource, error) {
	row := q.db.QueryRowContext(ctx, getResource, resourceID)
	var i Resource
	err := row.Scan(
		&i.ResourceID,
		&i.MaterialID,
		&i.Title,
		&i.Type,
		&i.ContentUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listResource = `-- name: ListResource :many
SELECT resource_id, material_id, title, type, content_url, created_at FROM resources
WHERE material_id = $1 AND resource_id = $2
ORDER BY resource_id
LIMIT $3
OFFSET $4
`

type ListResourceParams struct {
	MaterialID int64 `json:"material_id"`
	ResourceID int64 `json:"resource_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) ListResource(ctx context.Context, arg ListResourceParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResource,
		arg.MaterialID,
		arg.ResourceID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ResourceID,
			&i.MaterialID,
			&i.Title,
			&i.Type,
			&i.ContentUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResource = `-- name: UpdateResource :one
UPDATE resources
SET title = $3, type = $4, content_url = $5
WHERE material_id = $1 AND resource_id = $2
RETURNING resource_id, material_id, title, type, content_url, created_at
`

type UpdateResourceParams struct {
	MaterialID int64        `json:"material_id"`
	ResourceID int64        `json:"resource_id"`
	Title      string       `json:"title"`
	Type       TypeResource `json:"type"`
	ContentUrl string       `json:"content_url"`
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, updateResource,
		arg.MaterialID,
		arg.ResourceID,
		arg.Title,
		arg.Type,
		arg.ContentUrl,
	)
	var i Resource
	err := row.Scan(
		&i.ResourceID,
		&i.MaterialID,
		&i.Title,
		&i.Type,
		&i.ContentUrl,
		&i.CreatedAt,
	)
	return i, err
}
