// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: resources.sql

package db

import (
	"context"
	"database/sql"
)

const createResource = `-- name: CreateResource :one
INSERT INTO resources (
    title,
    type,
    content_url
) VALUES (
    $1, $2, $3
) RETURNING resource_id, course_id, assignment_id, title, type, content_url
`

type CreateResourceParams struct {
	Title      string       `json:"title"`
	Type       TypeResource `json:"type"`
	ContentUrl string       `json:"content_url"`
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, createResource, arg.Title, arg.Type, arg.ContentUrl)
	var i Resource
	err := row.Scan(
		&i.ResourceID,
		&i.CourseID,
		&i.AssignmentID,
		&i.Title,
		&i.Type,
		&i.ContentUrl,
	)
	return i, err
}

const deleteResource = `-- name: DeleteResource :exec
DELETE FROM resources
WHERE resource_id = $1 AND course_id = $2
`

type DeleteResourceParams struct {
	ResourceID int64         `json:"resource_id"`
	CourseID   sql.NullInt64 `json:"course_id"`
}

func (q *Queries) DeleteResource(ctx context.Context, arg DeleteResourceParams) error {
	_, err := q.db.ExecContext(ctx, deleteResource, arg.ResourceID, arg.CourseID)
	return err
}

const getResource = `-- name: GetResource :one
SELECT resource_id, course_id, assignment_id, title, type, content_url FROM resources
WHERE assignment_id = $1 AND course_id = $2
`

type GetResourceParams struct {
	AssignmentID sql.NullInt64 `json:"assignment_id"`
	CourseID     sql.NullInt64 `json:"course_id"`
}

func (q *Queries) GetResource(ctx context.Context, arg GetResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, getResource, arg.AssignmentID, arg.CourseID)
	var i Resource
	err := row.Scan(
		&i.ResourceID,
		&i.CourseID,
		&i.AssignmentID,
		&i.Title,
		&i.Type,
		&i.ContentUrl,
	)
	return i, err
}

const listResource = `-- name: ListResource :many
SELECT resource_id, course_id, assignment_id, title, type, content_url FROM resources
WHERE assignment_id = $1 AND course_id = $2
ORDER BY resource_id
LIMIT $3
OFFSET $4
`

type ListResourceParams struct {
	AssignmentID sql.NullInt64 `json:"assignment_id"`
	CourseID     sql.NullInt64 `json:"course_id"`
	Limit        int32         `json:"limit"`
	Offset       int32         `json:"offset"`
}

func (q *Queries) ListResource(ctx context.Context, arg ListResourceParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResource,
		arg.AssignmentID,
		arg.CourseID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ResourceID,
			&i.CourseID,
			&i.AssignmentID,
			&i.Title,
			&i.Type,
			&i.ContentUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResource = `-- name: UpdateResource :one
UPDATE resources
SET title = $3, type = $4, content_url = $5
WHERE assignment_id = $1 AND course_id = $2
RETURNING resource_id, course_id, assignment_id, title, type, content_url
`

type UpdateResourceParams struct {
	AssignmentID sql.NullInt64 `json:"assignment_id"`
	CourseID     sql.NullInt64 `json:"course_id"`
	Title        string        `json:"title"`
	Type         TypeResource  `json:"type"`
	ContentUrl   string        `json:"content_url"`
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, updateResource,
		arg.AssignmentID,
		arg.CourseID,
		arg.Title,
		arg.Type,
		arg.ContentUrl,
	)
	var i Resource
	err := row.Scan(
		&i.ResourceID,
		&i.CourseID,
		&i.AssignmentID,
		&i.Title,
		&i.Type,
		&i.ContentUrl,
	)
	return i, err
}
