// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: resources.sql

package db

import (
	"context"
)

const createResource = `-- name: CreateResource :one
INSERT INTO resources (
    material_id,
    title,
    type,
    content_url
) VALUES (
    $1, $2, $3, $4
) RETURNING resource_id, material_id, title, type, content_url, created_at
`

type CreateResourceParams struct {
	MaterialID int64        `json:"material_id"`
	Title      string       `json:"title"`
	Type       TypeResource `json:"type"`
	ContentUrl string       `json:"content_url"`
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.queryRow(ctx, q.createResourceStmt, createResource,
		arg.MaterialID,
		arg.Title,
		arg.Type,
		arg.ContentUrl,
	)
	var i Resource
	err := row.Scan(
		&i.ResourceID,
		&i.MaterialID,
		&i.Title,
		&i.Type,
		&i.ContentUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteResource = `-- name: DeleteResource :exec
DELETE FROM resources
WHERE resource_id = $1
`

func (q *Queries) DeleteResource(ctx context.Context, resourceID int64) error {
	_, err := q.exec(ctx, q.deleteResourceStmt, deleteResource, resourceID)
	return err
}

const getResource = `-- name: GetResource :one
SELECT resource_id, material_id, title, type, content_url, created_at FROM resources
WHERE resource_id = $1
`

func (q *Queries) GetResource(ctx context.Context, resourceID int64) (Resource, error) {
	row := q.queryRow(ctx, q.getResourceStmt, getResource, resourceID)
	var i Resource
	err := row.Scan(
		&i.ResourceID,
		&i.MaterialID,
		&i.Title,
		&i.Type,
		&i.ContentUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listResource = `-- name: ListResource :many
SELECT resource_id, material_id, title, type, content_url, created_at FROM resources
ORDER BY resource_id
LIMIT $1
OFFSET $2
`

type ListResourceParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListResource(ctx context.Context, arg ListResourceParams) ([]Resource, error) {
	rows, err := q.query(ctx, q.listResourceStmt, listResource, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ResourceID,
			&i.MaterialID,
			&i.Title,
			&i.Type,
			&i.ContentUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResource = `-- name: UpdateResource :one
UPDATE resources
SET title = $2, type = $3, content_url = $4
WHERE resource_id = $1
RETURNING resource_id, material_id, title, type, content_url, created_at
`

type UpdateResourceParams struct {
	ResourceID int64        `json:"resource_id"`
	Title      string       `json:"title"`
	Type       TypeResource `json:"type"`
	ContentUrl string       `json:"content_url"`
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error) {
	row := q.queryRow(ctx, q.updateResourceStmt, updateResource,
		arg.ResourceID,
		arg.Title,
		arg.Type,
		arg.ContentUrl,
	)
	var i Resource
	err := row.Scan(
		&i.ResourceID,
		&i.MaterialID,
		&i.Title,
		&i.Type,
		&i.ContentUrl,
		&i.CreatedAt,
	)
	return i, err
}
