// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: submissions.sql

package db

import (
	"context"
)

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (
    assignment_id,
    user_id
) VALUES (
    $1, $2
) RETURNING submission_id, assignment_id, user_id
`

type CreateSubmissionParams struct {
	AssignmentID int64 `json:"assignment_id"`
	UserID       int64 `json:"user_id"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.queryRow(ctx, q.createSubmissionStmt, createSubmission, arg.AssignmentID, arg.UserID)
	var i Submission
	err := row.Scan(&i.SubmissionID, &i.AssignmentID, &i.UserID)
	return i, err
}

const getsubmissionsByAssignment = `-- name: GetsubmissionsByAssignment :one
SELECT submission_id, assignment_id, user_id FROM submissions
WHERE assignment_id = $1 
LIMIT 1
`

func (q *Queries) GetsubmissionsByAssignment(ctx context.Context, assignmentID int64) (Submission, error) {
	row := q.queryRow(ctx, q.getsubmissionsByAssignmentStmt, getsubmissionsByAssignment, assignmentID)
	var i Submission
	err := row.Scan(&i.SubmissionID, &i.AssignmentID, &i.UserID)
	return i, err
}

const getsubmissionsByUser = `-- name: GetsubmissionsByUser :one
SELECT submission_id, assignment_id, user_id FROM submissions
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetsubmissionsByUser(ctx context.Context, userID int64) (Submission, error) {
	row := q.queryRow(ctx, q.getsubmissionsByUserStmt, getsubmissionsByUser, userID)
	var i Submission
	err := row.Scan(&i.SubmissionID, &i.AssignmentID, &i.UserID)
	return i, err
}

const listsubmissions = `-- name: Listsubmissions :many
SELECT submission_id, assignment_id, user_id FROM submissions
ORDER BY submission_id
LIMIT $1
OFFSET $2
`

type ListsubmissionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) Listsubmissions(ctx context.Context, arg ListsubmissionsParams) ([]Submission, error) {
	rows, err := q.query(ctx, q.listsubmissionsStmt, listsubmissions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Submission{}
	for rows.Next() {
		var i Submission
		if err := rows.Scan(&i.SubmissionID, &i.AssignmentID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
