// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: teachers.sql

package db

import (
	"context"
	"database/sql"
)

const createTeacher = `-- name: CreateTeacher :one
INSERT INTO teachers(
    full_name,
    email,
    user_name,
    hashed_password,
    is_active
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING teacher_id, admin_id, full_name, email, user_name, hashed_password, is_active, created_at
`

type CreateTeacherParams struct {
	FullName       string         `json:"full_name"`
	Email          string         `json:"email"`
	UserName       sql.NullString `json:"user_name"`
	HashedPassword string         `json:"hashed_password"`
	IsActive       bool           `json:"is_active"`
}

func (q *Queries) CreateTeacher(ctx context.Context, arg CreateTeacherParams) (Teacher, error) {
	row := q.db.QueryRowContext(ctx, createTeacher,
		arg.FullName,
		arg.Email,
		arg.UserName,
		arg.HashedPassword,
		arg.IsActive,
	)
	var i Teacher
	err := row.Scan(
		&i.TeacherID,
		&i.AdminID,
		&i.FullName,
		&i.Email,
		&i.UserName,
		&i.HashedPassword,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTeacher = `-- name: DeleteTeacher :exec
DELETE FROM teachers
WHERE teacher_id = $1
`

func (q *Queries) DeleteTeacher(ctx context.Context, teacherID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTeacher, teacherID)
	return err
}

const getTeacher = `-- name: GetTeacher :one
SELECT teacher_id, admin_id, full_name, email, user_name, hashed_password, is_active, created_at FROM teachers
WHERE teacher_id = $1
`

func (q *Queries) GetTeacher(ctx context.Context, teacherID int64) (Teacher, error) {
	row := q.db.QueryRowContext(ctx, getTeacher, teacherID)
	var i Teacher
	err := row.Scan(
		&i.TeacherID,
		&i.AdminID,
		&i.FullName,
		&i.Email,
		&i.UserName,
		&i.HashedPassword,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listTeacher = `-- name: ListTeacher :many
SELECT teacher_id, admin_id, full_name, email, user_name, hashed_password, is_active, created_at FROM teachers
WHERE admin_id = $1
ORDER BY teacher_id
LIMIT $2
OFFSET $3
`

type ListTeacherParams struct {
	AdminID sql.NullInt64 `json:"admin_id"`
	Limit   int32         `json:"limit"`
	Offset  int32         `json:"offset"`
}

func (q *Queries) ListTeacher(ctx context.Context, arg ListTeacherParams) ([]Teacher, error) {
	rows, err := q.db.QueryContext(ctx, listTeacher, arg.AdminID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Teacher{}
	for rows.Next() {
		var i Teacher
		if err := rows.Scan(
			&i.TeacherID,
			&i.AdminID,
			&i.FullName,
			&i.Email,
			&i.UserName,
			&i.HashedPassword,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeacher = `-- name: UpdateTeacher :one
UPDATE teachers
SET full_name = $2, email = $3, user_name = $4, hashed_password = $5, is_active = $6
WHERE teacher_id = $1
RETURNING teacher_id, admin_id, full_name, email, user_name, hashed_password, is_active, created_at
`

type UpdateTeacherParams struct {
	TeacherID      int64          `json:"teacher_id"`
	FullName       string         `json:"full_name"`
	Email          string         `json:"email"`
	UserName       sql.NullString `json:"user_name"`
	HashedPassword string         `json:"hashed_password"`
	IsActive       bool           `json:"is_active"`
}

func (q *Queries) UpdateTeacher(ctx context.Context, arg UpdateTeacherParams) (Teacher, error) {
	row := q.db.QueryRowContext(ctx, updateTeacher,
		arg.TeacherID,
		arg.FullName,
		arg.Email,
		arg.UserName,
		arg.HashedPassword,
		arg.IsActive,
	)
	var i Teacher
	err := row.Scan(
		&i.TeacherID,
		&i.AdminID,
		&i.FullName,
		&i.Email,
		&i.UserName,
		&i.HashedPassword,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
